apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rwd-webapp
    in-service: "true"
  name: rwd-webapp
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rwd-webapp
        in-service: "true"
    spec:
      containers:
      - env:
        - name: APP_NAME
          value: webapp
        image: 812436859307.dkr.ecr.us-east-1.amazonaws.com/rwd:1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: rwd-webapp
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "1024m"
            memory: 1536Mi
          requests:
            cpu: "300m"
            memory: 800Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rwd-webapp
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: rwd-webapp
  targetCPUUtilizationPercentage: 30
---
apiVersion: v1
kind: Service
metadata:
  name: rwd-webapp-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: rwd-webapp
    in-service: "true"
  sessionAffinity: None
  type: LoadBalancer
