export default {
  getStoreLocatorByLatLngResponse: {
    result: [
      {
        bossMaxDate: '11/03/2019',
        bossMinDate: '10/29/2019',
        brands: ['TCP'],
        city: 'brooklyn',
        counter: '1',
        country: 'US',
        distanceFromUserToStore: '0',
        distanceMeasurement: 'KTM',
        isStoreBOSSEligible: '1',
        latitude: '40.69112',
        longitude: '-73.98625',
        phone: '(718) 243-1150',
        postalcode: '11201',
        readableDistanceMeasurement: 'kilometers',
        state: 'NY',
        storeName: 'fulton street',
        storeType: 'PLACE',
        storeUniqueID: '110850',
        storehours: {},
        streetLine1: '471-485 fulton street',
        streetLine2: '',
      },
      {
        bossMaxDate: '11/04/2019',
        bossMinDate: '10/28/2019',
        brands: ['TCP'],
        city: 'new york',
        counter: '2',
        country: 'US',
        distanceFromUserToStore: '3.05',
        distanceMeasurement: 'KTM',
        isStoreBOSSEligible: '1',
        latitude: '40.71855',
        longitude: '-73.98745',
        phone: '(212) 982-8401',
        postalcode: '10002',
        readableDistanceMeasurement: 'kilometers',
        state: 'NY',
        storeName: '126 delancey street',
        storeType: 'PLACE',
        storeUniqueID: '114178',
        storehours: {},
        streetLine1: '126 delancey street',
        streetLine2: '',
      },
      {
        bossMaxDate: '11/03/2019',
        bossMinDate: '10/28/2019',
        brands: ['TCP'],
        city: 'brooklyn',
        counter: '3',
        country: 'US',
        distanceFromUserToStore: '3.21',
        distanceMeasurement: 'KTM',
        isStoreBOSSEligible: '1',
        latitude: '40.68056',
        longitude: '-73.95081',
        phone: '(718) 623-2317',
        postalcode: '11216',
        readableDistanceMeasurement: 'kilometers',
        state: 'NY',
        storeName: 'bed stuy (fulton st)',
        storeType: 'PLACE',
        storeUniqueID: '111879',
        storehours: {},
        streetLine1: '1244 fulton st',
        streetLine2: '',
      },
      {
        bossMaxDate: '11/02/2019',
        bossMinDate: '10/28/2019',
        brands: ['TCP'],
        city: 'new york',
        counter: '4',
        country: 'US',
        distanceFromUserToStore: '5',
        distanceMeasurement: 'KTM',
        isStoreBOSSEligible: '1',
        latitude: '40.73603',
        longitude: '-73.98943',
        phone: '(212) 529-2201',
        postalcode: '10003',
        readableDistanceMeasurement: 'kilometers',
        state: 'NY',
        storeName: 'union square',
        storeType: 'PLACE',
        storeUniqueID: '110961',
        storehours: {},
        streetLine1: '36 union sq. east',
        streetLine2: '',
      },
      {
        bossMaxDate: '11/01/2019',
        bossMinDate: '10/29/2019',
        brands: ['TCP'],
        city: 'jersey city',
        counter: '5',
        country: 'US',
        distanceFromUserToStore: '5.89',
        distanceMeasurement: 'KTM',
        isStoreBOSSEligible: '1',
        latitude: '40.72614',
        longitude: '-74.03881',
        phone: '(201) 963-5537',
        postalcode: '07310',
        readableDistanceMeasurement: 'kilometers',
        state: 'NJ',
        storeName: 'newport center',
        storeType: 'PLACE',
        storeUniqueID: '110715',
        storehours: {},
        streetLine1: '30 mall drive west',
        streetLine2: 'space a61',
      },
    ],
  },
};
