// Note: use zipObj to simplify creation of object where keys/values are equal.
import { zipObj } from '../utils/utils';

/**
 * Names of basic tracking events.
 * @type {Object}
 * @see https://bitbucket.org/TCP_BitBucket_Admin/tcp_omniture_-_marketing/src/master/src/global/data/constants/event-names.js
 */
export const basicEventNames = {
  linkClick: 'trackLinkEvent',
  pageView: 'trackPageView',
  navigationClick: 'navigation click',
};

/**
 * Names of service events.
 * @type {Object}
 * @see https://bitbucket.org/TCP_BitBucket_Admin/tcp_omniture_-_marketing/src/master/src/global/data/constants/endpoints.js
 */
export const serviceEventNames = zipObj([
  'acceptOrDeclineWIC',
  'addAddress',
  'addCheckout',
  'addChild',
  'addCoupons',
  'addCreditCardDetails',
  'addCustomerRegistration',
  'addGiftCardToAccount',
  'addGiftOptions',
  'addOrderBopisItem',
  'addOrderItem',
  'addOrUpdateWishlist',
  'addPaymentInstruction',
  'addProductToCart',
  'addShipToStore',
  'addSignUpEmail',
  'addWishListItem',
  'applicationKillSwitches',
  'authToken',
  'checkout',
  'claimPoints',
  'createWishList',
  'createWishListForUser',
  'deleteAddressDetails',
  'deleteAddressOnAccount',
  'deleteAllItemsInCart',
  'deleteChild',
  'deleteCreditCardDetails',
  'deleteCreditCardOnAccount',
  'deleteFavoriteStore',
  'deleteGiftCardOnAccount',
  'deletePaymentInstruction',
  'deleteWishListForUser',
  'deleteWishListItemForUser',
  'editWishList',
  'findStoresbyLatitudeandLongitude',
  'getAddressFromBook',
  'getAddressVerification',
  'getAllAvailableCouponsAndPromos',
  'getAllSfl',
  'getAssignedPromotioncodeInfo',
  'getAutoSuggestions',
  'getAutoSuggestionsUnbxd',
  'getBOPISInventoryDetails',
  'getCartInfo',
  'getChildren',
  'getCountryHandler',
  'getCountryList',
  'getCoupon',
  'getCreditCardDetails',
  'getDetailedOrderHistory',
  'getESpot',
  'getFavoriteStore',
  'getGifCardBalance',
  'getHeaderService',
  'getInventoryForOutfits',
  'getListofDefaultWishlist',
  'getListofWishList',
  'getMyPointHistory',
  'getOrderConfirmation',
  'getOrderDetails',
  'getOrderHistory',
  'getOrderReview',
  'getOrdersAndCouponDetails',
  'getOrderSummary',
  'getPaymentInfo',
  'getPointsHistory',
  'getPointsService',
  'getProductDetails',
  'getProductInfoById',
  'getProductsByOutfits',
  'getProductsBySearchTerm',
  'getProductviewbyCategory',
  'getRegisteredUserDetailsInfo',
  'getReservationHistory',
  'getShipmentMethods',
  'getSitePromotions',
  'getSKUDetails',
  'getSKUInventoryandProductCounterDetails',
  'getStaticESpot',
  'getStoreandProductInventoryInfo',
  'getStoreInfoByLocationId',
  'getStoreLocationByCountry',
  'getSwatchesAndSizeInfo',
  'getUnqualifiedItems',
  'getUserBopisStores',
  'getUserPaymentInformation',
  'getUserWishlists',
  'getWishListbyId',
  'giftOptionsCmd',
  'instantCreditApplication',
  'internationalCheckoutSettings',
  'logon',
  'logout',
  'makeWishListasDefault',
  'modifyCreditCardDetails',
  'moveWishListItem',
  'newReservationLookUp',
  'orderLookUp',
  'paypalAuth',
  'paypalLookUp',
  'persoanlizedCoupons',
  'preCheckout',
  'prescreenApplication',
  'processPreScreenCodeValidation',
  'processPreScreenOffer',
  'removeCouponOrPromo',
  'requestPassword',
  'reservationLookUp',
  'sendEmailForContactUs',
  'setDefaultShippingAddress',
  'setFavoriteStore',
  'setShipToHome',
  'shareWishListForUser',
  'smsMarketingSignup',
  'sortingWishList',
  'startExpressCheckout',
  'updateAddress',
  'updateAirMilesInfo',
  'updateCheckout',
  'updateChild',
  'updateDeleteItem',
  'updateDescriptionofWishList',
  'updateFavoriteStore',
  'updateMultiSelectItemsToRemove',
  'updateOrderBopisItem',
  'updateOrderItem',
  'updatePaymentInstruction',
  'updateProfileInfo',
  'updatesAccountDataForRegisteredUser',
  'updateShippingInfo',
  'updateShippingMethodSelection',
  'updateUserShippingAddress',
  'updateWishListItem',
]);
