export default {
  'footer__social-link--fb': '/static/images/facebook.svg',
  'footer__social-link--tw': '/static/images/twitter.svg',
  'footer__social-link--ig': '/static/images/instagram.svg',
  'footer__social-link--pt': '/static/images/pinterest.svg',
  'icon-carrot-grey': '/static/images/carrot-icon-grey.svg',
  'icon-carrot-white': '/static/images/carrot-icon-white.svg',
  'icon-done': '/static/images/done.svg',
  'footer__mpr-container--col1': '/static/images/mp-rewards-orange.png',
  'footer__mpr-container--col2': '/static/images/mp-rewards-blue.png',
  'header__brand-tab--tcp': '/static/images/tcp-logo.svg',
  'header__brand-tab-gymboree': '/static/images/gymboree-logo.svg',
  'icon-play': '/static/images/play.svg',
  'icon-pause': '/static/images/play.svg',
};
