export default {
  'footer__social-link--fb': '/static/images/facebook.svg',
  'footer__social-link--tw': '/static/images/twitter.svg',
  'footer__social-link--ig': '/static/images/instagram.svg',
  'footer__social-link--pt': '/static/images/pinterest.svg',
  // TODO - Remove the header__promo-text-banner when the styles start coming up from CMS
  'header__promo-text-banner': '/static/images/at-icon.svg',
  'blue-email': '/static/images/at-icon.svg',
  'green-dollar': '/static/images/dollar-sign-icon.svg',
  'orange-schedule': '/static/images/clock-icon.svg',
  'icon-carrot-grey-large': '/static/images/carrot-icon-grey.svg',
  'icon-carrot-black-small': '/static/images/carrot-small-black.svg',
  'icon-carrot-white': '/static/images/carrot-icon-white.svg',
  'icon-done': '/static/images/done.svg',
  'footer__mpr-container--col1': '/static/images/mp-rewards-orange.png',
  'footer__mpr-container--col2': '/static/images/mp-rewards-blue.png',
  'header__brand-tab--tcp': '/static/images/tcp-logo.svg',
  'header__brand-tab-gymboree': '/static/images/gymboree-logo.svg',
  'icon-play': '/static/images/play.svg',
  'icon-pause': '/static/images/pause.svg',
  'gift-card-icon': '/static/images/gift-card-small.png',
  'icon-card-smile': '/static/images/card-smile.png',
  'credit-card': '/static/images/credit-card.png',
  'gift-card': '/static/images/gift-card.png',
  'disc-small': '/static/images/discover.svg',
  'mc-small': '/static/images/mastercard.svg',
  'amex-small': '/static/images/amex.svg',
  'place-card-small': '/static/images/TCP-CC.svg',
  'visa-small': '/static/images/visa.svg',
  'gift-card-small': '/static/images/TCP-gift.svg',
  'venmo-blue-acceptance-mark': '/static/images/venmo.svg',
  down_arrow_icon: '/static/images/down_arrow_icon.png',
  active_icon: '/static/images/active_icon.png',
  'carousel-big-carrot': '/static/images/right-carousel-carrot.svg',
};
