// this is temporary file and will be removed once label integration done
const labels = {
  addNewAddressCTA: 'ADD NEW ADDRESS',
  createAddressBookMsg: 'Create an Address Book to check out faster!',
  createAddressBookBenefitMsg:
    'Add and save up to 5 shipping addresses so you can speed through the checkout process the next time you shop',
  defaultShipping: 'DEFAULT SHIPPING',
  billing: 'BILLING',
  shipping: 'SHIPPING',
  makeDefault: 'Make Default',
  edit: 'Edit',
  delete: 'Delete',
  defaultBilling: 'DEFAULT BILLING',
  defaultShippingSuccessMessage: 'Your account has been updated',
  defaultShippingSuccessFail: 'Your action could not be completed due to a system error',
  successMessage: 'Your account has been updated',
  errorMessage: 'Your action could not be completed due to a system error',
  deleteAddressHeading: 'DELETE ADDRESS',
  deleteAddressTitle: 'Are you sure you want to delete this address?',
  cancel: "No, Don't Delete",
  deleteConfirm: 'Yes, Delete',
  addressBookHeading: 'ADDRESS BOOK',
  acc_lbl_first_name: 'First Name',
  acc_lbl_last_name: 'Last Name',
  acc_lbl_address_line1: 'Address Line 1',
  acc_lbl_address_line2: 'Address Line 2 (Optional)',
  acc_lbl_city: 'City',
  acc_lbl_state: 'State',
  acc_lbl_province: 'Province',
  acc_lbl_zip_code: 'Zip Code',
  acc_lbl_postal_code: 'Postal Code',
  acc_lbl_country: 'Country',
  acc_lbl_phone_number: 'Phone Number',
  acc_lbl_cancel_cta: 'CANCEL',
  acc_lbl_add_address_cta: 'ADD ADDRESS',
  acc_lbl_update_address_cta: 'UPDATE',
  acc_lbl_set_default: 'Set as default shipping address',
  acc_lbl_verify_your_address_header: 'Verify Your Address',
  acc_lbl_verify_your_address_heading_add: 'Add Address',
  acc_lbl_verify_your_address_heading_edit: 'EDIT ADDRESS',
  acc_label_verify_your_address_AE09:
    'There may be an issue with your address as entered. Please double check it, or if you believe the address is correct you can continue to the next step.',
  acc_label_verify_your_address_AE10:
    'The house / building number is not valid. Please review and confirm your address.',
  acc_label_verify_your_address_AE11:
    'The house / building number is missing from your address. Please review and confirm your address.',
  acc_label_verify_your_address_AE12:
    'The house / building number is not valid. Please review and confirm your address.',
  acc_label_verify_your_address_DEFAULT:
    'There may be an issue with your address as entered. Please double check it, or select from the below.',
  acc_lbl_you_entered: 'YOU ENTERED',
  acc_lbl_we_suggest: 'WE SUGGEST',
  acc_lbl_optional_address_line: 'Apartment or suite number',
  acc_lbl_continue_cta: 'CONTINUE',
  acc_lbl_edit_address_cta: 'EDIT ADDRESS',
  acc_lbl_add_address_form_heading: 'Add New Shipping Address',
  acc_lbl_edit_address_form_heading: 'EDIT SHIPPING ADDRESS',
};

export default labels;
