import PropTypes from 'prop-types';

const propTypes = {
  addressLabels: PropTypes.shape({}).isRequired,
  handleSubmit: PropTypes.func.isRequired,
  className: PropTypes.string,
  dispatch: PropTypes.func.isRequired,
  isOrderUpdateChecked: PropTypes.bool,
  smsSignUpLabels: PropTypes.shape({}).isRequired,
  selectedShipmentId: PropTypes.string,
  addressPhoneNo: PropTypes.number,
  emailSignUpLabels: PropTypes.shape({}).isRequired,
  isGuest: PropTypes.bool,
  isUsSite: PropTypes.bool,
  orderHasPickUp: PropTypes.bool,
  shipmentMethods: PropTypes.shape([]),
  loadShipmentMethods: PropTypes.func.isRequired,
  routeToPickupPage: PropTypes.func.isRequired,
  isSaveToAddressBookChecked: PropTypes.bool,
  userAddresses: PropTypes.shape([]),
  onFileAddressKey: PropTypes.string,
  isMobile: PropTypes.bool,
  newUserPhoneNo: PropTypes.number,
  shippingAddressId: PropTypes.string,
  setAsDefaultShipping: PropTypes.bool,
  addNewShippingAddressData: PropTypes.func.isRequired,
  updateShippingMethodSelection: PropTypes.func.isRequired,
  saveToAddressBook: PropTypes.bool,
  updateShippingAddressData: PropTypes.func.isRequired,
  toggleAddNewAddress: PropTypes.func.isRequired,
  isAddNewAddress: PropTypes.bool,
  updateShippingAddress: PropTypes.func.isRequired,
  addNewShippingAddress: PropTypes.func.isRequired,
  defaultAddressId: PropTypes.string,
  defaultShipmentId: PropTypes.number,
  labels: PropTypes.shape({}).isRequired,
  syncErrors: PropTypes.shape({}),
  showAccordian: PropTypes.bool.isRequired,
};

const defaultProps = {
  className: '',
  isOrderUpdateChecked: false,
  selectedShipmentId: null,
  addressPhoneNo: null,
  isGuest: true,
  isUsSite: true,
  orderHasPickUp: false,
  shipmentMethods: null,
  isSaveToAddressBookChecked: false,
  userAddresses: [],
  onFileAddressKey: null,
  isMobile: false,
  newUserPhoneNo: null,
  shippingAddressId: null,
  setAsDefaultShipping: false,
  saveToAddressBook: false,
  isAddNewAddress: false,
  defaultAddressId: null,
  defaultShipmentId: null,
  syncErrors: {},
  showAccordian: true,
};

export { propTypes, defaultProps };
