const LoyaltyBannerLabels = {
  // lbl_loyaltyBanner_youCanEarn: 'You can earn ',
  // lbl_loyaltyBanner_youllEarn: "You'll earn ",
  // lbl_loyaltyBanner_pointsOnPurchase: ' points on this purchase!',
  // lbl_loyaltyBanner_becomeMember: 'Become a member to get a ',
  // lbl_loyaltyBanner_reward: ' Reward ',
  // lbl_loyaltyBanner_rewardOnPurchase: ' on this purchase!',
  // lbl_loyaltyBanner_youllGetA: "You'll get a ",
  // lbl_loyaltyBanner_withThisPurchase: ' with this purchase!',
  // lbl_loyaltyBanner_save30Today: 'SAVE 30% TODAY! ',
  // lbl_loyaltyBanner_earnDoublePoints:
  //   '+ EARN DOUBLE POINTS* when you open & use a MY PLACE REWARDS CREDIT CARD',
  // lbl_loyaltyBanner_currentSubtotal: 'Current Subtotal: ',
  // lbl_loyaltyBanner_estimatedSubtotal: 'Estimated Subtotal with a My Place Rewards Credit Card: ',
  // lbl_loyaltyBanner_applyNow: 'Apply Now',
  // lbl_loyaltyBanner_learnMore: 'Learn More',
  youCanEarn: 'You can earn ',
  youllEarn: 'You"ll earn ',
  pointsOnPurchase: ' points on this purchase!',
  becomeMember: 'Become a member to get a ',
  reward: ' Reward ',
  rewardOnPurchase: ' on this purchase!',
  youllGetA: 'You"ll get a ',
  withThisPurchase: ' with this purchase!',
  save30Today: 'SAVE 30% TODAY! ',
  earnDoublePoints: '+ EARN DOUBLE POINTS* when you open & use a MY PLACE REWARDS CREDIT CARD',
  currentSubtotal: 'Current Subtotal: ',
  estimatedSubtotal: 'Estimated Subtotal with a My Place Rewards Credit Card: ',
  applyNow: 'Apply Now',
  learnMore: 'Learn More',

  youCanEarnPoints: 'You can earn #pointNumber# points on this purchase!',
  youllEarnPoints: 'You"ll earn #pointNumber# points on this purchase!',
  becomeMemberOnThisPurchase: 'Become a member to get a #Reward# on this purchase!',
  youllGetWithThisPurchase: 'You"ll get a #Reward# with this purchase!',
  youllEarnPointsPlcc: 'YOU’LL EARN #pointNumber# POINTS',
  youllGetARewardPlcc: 'YOU’LL GET A #REWARD#',
  onThisPurchasePlcc: 'ON THIS PURCHASE!',
  whenYouCheckOutPlcc: 'when you check out with your',
  myPlaceRewardsCCPlcc: 'MY PLACE REWARDS CREDIT CARD',
  thatsSomePointsFromReward: 'That’s #pointNumber# points from a $5 Reward.',
};

export default LoyaltyBannerLabels;
