const LoyaltyBannerLabels = {
  // lbl_loyaltyBanner_youCanEarnPoints: 'You can earn #estimatedRewardsVal# points on this purchase!',
  // lbl_loyaltyBanner_youllEarnPoints: 'You"ll earn #estimatedRewardsVal# points on this purchase!',
  // lbl_loyaltyBanner_becomeMemberOnThisPurchase: 'Become a member to get a #estimatedRewardsVal# on this purchase!',
  // lbl_loyaltyBanner_youllGetWithThisPurchase: 'You"ll get a #estimatedRewardsVal# with this purchase!',
  // lbl_loyaltyBanner_youllEarnPointsPlcc: 'YOU’LL EARN #estimatedRewardsVal# POINTS <br/> ON THIS PURCHASE!',
  // lbl_loyaltyBanner_youllGetARewardPlcc: 'YOU’LL GET A #estimatedRewardsVal# <br/> ON THIS PURCHASE!',
  // lbl_loyaltyBanner_whenYouCheckOutPlcc: 'when you check out with your <br/> MY PLACE REWARDS CREDIT CARD',
  // lbl_loyaltyBanner_thatsSomePointsFromReward: 'That’s #pointsToNextReward# points from a $5 Reward.',
  // lbl_loyaltyBanner_save30Today: 'SAVE 30% TODAY! ',
  // lbl_loyaltyBanner_earnDoublePoints: '+ EARN DOUBLE POINTS* when you open & use a MY PLACE REWARDS CREDIT CARD',
  // lbl_loyaltyBanner_currentSubtotal: 'Current Subtotal: ',
  // lbl_loyaltyBanner_estimatedSubtotal: 'Estimated Subtotal with a My Place Rewards Credit Card: ',
  // lbl_loyaltyBanner_applyNow: 'Apply Now',
  // lbl_loyaltyBanner_learnMore: 'Learn More',

  youCanEarnPoints: 'You can earn #estimatedRewardsVal# points on this purchase!',
  youllEarnPoints: 'You"ll earn #estimatedRewardsVal# points on this purchase!',
  becomeMemberOnThisPurchase: 'Become a member to get a #estimatedRewardsVal# on this purchase!',
  youllGetWithThisPurchase: 'You"ll get a #estimatedRewardsVal# with this purchase!',
  youllEarnPointsPlcc: 'YOU’LL EARN #estimatedRewardsVal# POINTS <br/> ON THIS PURCHASE!',
  youllGetARewardPlcc: 'YOU’LL GET A #estimatedRewardsVal# <br/> ON THIS PURCHASE!',
  whenYouCheckOutPlcc: 'when you check out with your <br/> MY PLACE REWARDS CREDIT CARD',
  thatsSomePointsFromReward: 'That’s #pointsToNextReward# points from a $5 Reward.',
  save30Today: 'SAVE 30% TODAY! ',
  earnDoublePoints: '+ EARN DOUBLE POINTS* when you open & use a MY PLACE REWARDS CREDIT CARD',
  currentSubtotal: 'Current Subtotal: ',
  estimatedSubtotal: 'Estimated Subtotal with a My Place Rewards Credit Card: ',
  applyNow: 'Apply Now',
  learnMore: 'Learn More',
};

export default LoyaltyBannerLabels;
