import {
  APICONFIG_ACTION_PATTERN,
  SESSIONCONFIG_ACTION_PATTERN,
} from '../../constants/reducer.constants';

export default {
  XAPP_CONFIG_MODULE: 'xappConfig',
  BOOTSTRAP_API: 'BOOTSTRAP_API',
  SITE_CONFIG: 'SITE_CONFIG',
  SET_API_CONFIG: `${APICONFIG_ACTION_PATTERN}SET_API_CONFIG`,
  GET_MODULEX_CONTENT: 'GET_MODULEX_CONTENT',
  SET_MODULEX_CONTENT: 'SET_MODULEX_CONTENT',
  LOAD_LAYOUT_DATA: 'LOAD_LAYOUT_DATA',
  LOAD_LABELS_DATA: 'LOAD_LABELS_DATA',
  SET_LABELS_DATA: 'SET_LABELS_DATA',
  LOAD_COMPONENT_LABELS_DATA: 'LOAD_COMPONENT_LABELS_DATA',
  LOAD_SEO_DATA: 'LOAD_SEO_DATA',
  SET_SEO_DATA: 'SET_SEO_DATA',
  LOAD_PAGE_SEO_DATA: 'LOAD_PAGE_SEO_DATA',
  LOAD_MODULES_DATA: 'LOAD_MODULES_DATA',
  LOAD_USER_DATA: 'GET_USER_INFO',
  SET_XAPP_CONFIG: `${SESSIONCONFIG_ACTION_PATTERN}SET_XAPP_CONFIG`,
  SET_BOSS_BOPIS_FLAGS: `${SESSIONCONFIG_ACTION_PATTERN}SET_BOSS_BOPIS_FLAGS`,
  SET_COUNTRY: `${SESSIONCONFIG_ACTION_PATTERN}SET_COUNTRY`,
  SET_LANGUAGE: `${SESSIONCONFIG_ACTION_PATTERN}SET_LANGUAGE`,
  SET_CURRENCY: `${SESSIONCONFIG_ACTION_PATTERN}SET_CURRENCY`,
  SET_DEVICE_INFO: 'SET_DEVICE_INFO',
  SET_OPTIMIZELY_FEATURES_LIST: 'SET_OPTIMIZELY_FEATURES_LIST',
  FETCH_PAGE_LAYOUT: 'FETCH_PAGE_LAYOUT',
};

export const LABELS = {
  labels: 'labels',
  global: 'global',
  modules: 'modules',
  account: 'account',
  bagPage: 'bag',
  checkout: 'checkout',
};

export const SEO_DATA = {
  seoData: 'seoData',
  home: '/home',
};
