const mockLeftSideNavigation = {
    data: {
      subnavigation: [
        {
          subSections: null,
          leafLink: {
            url: '/helpCenter',
            id: 'help-center-home',
            text: 'Help Center Home',
            displayName: 'Help Center Home',
            component: 'help-center-home',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: '/account/place-rewards',
            text: 'My Place Rewards',
            id: 'place-rewards',
            displayName: 'My Place Rewards',
            component: 'place-rewards',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: '/account/favorites',
            text: 'My Place Rewards Program',
            id: 'my-place-rewards-program',
            displayName: 'My Place Rewards Program',
            component: 'my-place-rewards-program',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: '/account/extra-points',
            text: 'Earn Extra Points',
            id: 'extra-points',
            displayName: 'Earn Extra Points',
            component: 'extra-points',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: '/account/favorites',
            text: 'My Place Rewards Credit Card',
            id: 'my-place-rewards-credit-card',
            displayName: 'My Place Rewards Credit Card',
            title: 'my-place-rewards-credit-card',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: null,
            text: 'Coupons and Promotions',
            id: 'coupons-and-promotions',
            displayName: 'Coupons and Promotions',
            component: 'coupons-and-promotions',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: null,
            text: 'Help With My Order',
            id: 'help-with-my-order',
            displayName: 'Help With My Order',
            component: 'help-with-my-order',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: null,
            text: 'Online Ordering',
            id: 'online-ordering',
            displayName: 'Online Ordering',
            component: 'online-ordering',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: null,
            text: 'Policies',
            id: 'policies',
            displayName: 'Policies',
            component: 'policies',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: null,
            text: 'Terms and Conditions',
            id: 'terms-and-conditions',
            displayName: 'Terms and Conditions',
            component: 'terms-and-conditions',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: null,
            text: 'Mobile Terms and Conditions',
            id: 'mobile-terms-and-conditions',
            displayName: 'Mobile Terms and Conditions',
            component: 'mobile-terms-and-conditions',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: null,
            text: 'Shipping to the U.S.',
            id: 'shipping-to-the-U.S.',
            displayName: 'Shipping to the U.S.',
            component: 'shipping-to-the-U.S.',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: null,
            text: 'Tools',
            id: 'tools',
            displayName: 'Tools',
            component: 'tools',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
        {
          subSections: null,
          leafLink: {
            url: null,
            text: 'Contact Us',
            id: 'contact-us',
            displayName: 'Contact Us',
            component: 'contact-us',
            target: '',
            external: 0,
            __typename: 'Link',
          },
          __typename: 'HelpCenterNavigationContent',
        },
      ],
    },
  };
  
  export default mockLeftSideNavigation;
  