/* eslint-disable max-lines */
/* eslint-disable sonarjs/no-duplicate-string */

export default {
  searchMetaData: {
    status: 0,
    queryTime: 25,
    queryParams: {
      pagetype: 'boolean',
      'log.response': 'false',
      'module.exclude': 'personalization',
      'alternate.op': 'true',
      'q.op': 'AND',
      variants: 'true',
      'variants.count': '0',
      'f.categoryPath.facet.limit': '100',
      'req.rm.promotionEngine': 'true',
      selectedfacet: 'true',
      activeExperiment: 'false',
      'facet.multiselect': 'true',
      'taxonomy.removeProd': 'true',
      'popularProducts.count': '0',
      start: '20',
      'req.rm.asterix': 'true',
      'p-id': 'categoryPathId:"47502>47535>54069"',
      rows: '20',
      version: 'V2',
      enableTaxonomy: 'false',
      'variants.relevant': 'false',
      uc_param: 'A/B-Test',
      'user.behaviour': 'true',
      fields:
        'alt_img,style_partno,giftcard,TCPProductIndUSStore,TCPFitMessageUSSstore,TCPFit,TCPWebOnlyFlagUSStore,TCPWebOnlyFlagCanadaStore,TCPSwatchesUSStore,top_rated,TCPSwatchesCanadaStore,product_name,TCPColor,imagename,productid,uniqueId,favoritedcount,TCPBazaarVoiceReviewCount,categoryPath3_fq,categoryPath3,categoryPath3_catMap,categoryPath2_catMap,product_short_description,min_list_price,min_offer_price,TCPBazaarVoiceRating,seo_token,prodpartno,banner,facets,auxdescription,list_of_attributes,numberOfProducts,redirect,searchMetaData,didYouMean,TCPLoyaltyPromotionTextUSStore,TCPLoyaltyPLCCPromotionTextUSStore,TcpBossCategoryDisabled,TcpBossProductDisabled,long_product_title,TCPOutOfStockFlagUSStore,TCPOutOfStockFlagCanadaStore,product_type,products,low_offer_price,high_offer_price,low_list_price,high_list_price',
      enablePopularity: 'true',
    },
  },
  response: {
    numberOfProducts: 32,
    start: 20,
    products: [
      {
        uniqueId: '3003099_32E5',
        favoritedcount: 1100.0,
        TCPBazaarVoiceReviewCount: 4.0,
        min_list_price: 16.95,
        list_of_attributes:
          'TCPInventoryFlagUSStore:1;TCPInventoryFlagCanadaStore:1;TCPColor:WHITE;TCPInventoryMessageCanadaStore:NO_INVENTORY_MESSAGE;TCPInventoryMessageUSStore:NO_INVENTORY_MESSAGE;TCPProductArrivalDateUSStore:6/17/2019;TCPProductArrivalDateCanadaStore:6/17/2019;TCPSwatchesCanadaStore:3003099_32E5#LITTLE LAMB;TCPSwatchesUSStore:3003099_32E5#LITTLE LAMB;TCPBazaarVoiceRating:5.0;TCPMerchantTagUSStore:50% OFF;TCPMerchantTagCanadaStore:50% OFF;TCPBazaarVoiceReviewCount:4.0',
        imagename: '3003099_32E5',
        TCPColor: 'WHITE',
        auxdescription: 'LITTLE LAMB',
        TCPSwatchesCanadaStore: '3003099_32E5#LITTLE LAMB',
        product_name: 'Baby And Toddler Girls Long Sleeve Butterfly Print Smocked Top',
        long_product_title: 'Baby And Toddler Girls Long Sleeve Butterfly Print Smocked Top',
        style_partno: '3003099',
        TCPSwatchesUSStore: '3003099_32E5#LITTLE LAMB',
        TCPBazaarVoiceRating: 5.0,
        seo_token: 'Baby-And-Toddler-Girls-Long-Sleeve-Butterfly-Print-Smocked-Top-3003099-32E5',
        min_offer_price: 8.48,
        prodpartno: '3003099_32E5',
        alt_img: '{"3003099_32E5": "3003099_32E5-1.jpg,3003099_32E5-2.jpg"}',
        productid: '1309194',
        low_list_price: 16.95,
        low_offer_price: 8.48,
        categoryPath3: ['Long Sleeve', 'Tops'],
        categoryPath3_fq: ['Baby>Baby Girl>Tops', 'Toddler Girl>Tops>Long Sleeve'],
        categoryPath2_catMap: ['47504>50502|Baby>Baby Girl', '47502>47535|Toddler Girl>Tops'],
        categoryPath3_catMap: [
          '47504>50502>453003|Baby>Baby Girl>Tops',
          '47502>47535>54069|Toddler Girl>Tops>Long Sleeve',
        ],
      },
    ],
  },
  facets: {
    text: {
      list: [
        {
          facetName: 'categoryPath2_uFilter',
          filterField: 'categoryPath2_uFilter',
          values: [
            'Tops',
            32,
            'Baby Girl',
            27,
            'Online Only',
            13,
            'New Arrivals',
            10,
            'Essentials Shop',
            8,
            'School Uniforms',
            4,
            'Sets',
            4,
            'Active',
            3,
            'Bottoms',
            3,
            'Leggings',
            3,
            'Shop Now',
            3,
          ],
          displayName: 'Category',
          position: 1,
        },
        {
          facetName: 'TCPColor_uFilter',
          filterField: 'TCPColor_uFilter',
          values: [
            'WHITE',
            11,
            'PINK',
            10,
            'BLUE',
            3,
            'BLACK',
            2,
            'RED',
            2,
            'GRAY',
            1,
            'MULTI',
            1,
            'ORANGE',
            1,
            'PURPLE',
            1,
          ],
          displayName: 'Color',
          position: 2,
        },
        {
          facetName: 'v_tcpsize_uFilter',
          filterField: 'v_tcpsize_uFilter',
          values: [
            'EF_6-9 M',
            31,
            'EJ_9-12 M',
            30,
            'EM_12-18 M',
            30,
            'EP_18-24 M',
            31,
            'ET_2T',
            31,
            'EX_3T',
            27,
            'EZ_4T',
            27,
            'FB_5T',
            27,
          ],
          displayName: 'Size',
          position: 3,
        },
        {
          facetName: 'unbxd_price_range_uFilter',
          filterField: 'unbxd_price_range_uFilter',
          values: ['$10 - $19.99', 10, '$10 and Under', 21, '$20 - $29.99', 1],
          displayName: 'Price',
          position: 4,
        },
        {
          facetName: 'v_tcpfit_unbxd_uFilter',
          filterField: 'v_tcpfit_unbxd_uFilter',
          values: ['Regular', 32],
          displayName: 'Fit',
          position: 5,
        },
        {
          facetName: 'gender_uFilter',
          filterField: 'gender_uFilter',
          values: ['Girl', 32],
          displayName: 'Gender',
          position: 6,
        },
        {
          facetName: 'age_group_uFilter',
          filterField: 'age_group_uFilter',
          values: ['AC_Toddler (6M - 5T)', 1, 'AD_Baby (0 - 18M)', 31],
          displayName: 'Size Range',
          position: 7,
        },
      ],
    },
    multilevel: {
      bucket: {},
    },
  },
};

export const productRes = {};

export const promoCombinationMock = {
  cid: '<uuid>',
  typ: 'promoCombination',
  sub: 'plp',
  val: {
    top: [
      {
        typ: 'slot',
        sub: 'slot_1',
        val: {
          cid: 'b8119dc0-5bd9-4047-a2cb-c8226eeb4e80',
          typ: 'module',
          sub: 'moduleA',
          val: '',
        },
      },
      {
        typ: 'slot',
        sub: 'slot_6',
        val: {
          cid: '27166e47-4fd2-4701-8fb2-bf8e3d09e36d',
          typ: 'module',
          sub: 'moduleL',
          val: '',
        },
      },
      {
        typ: 'slot',
        sub: 'slot_8',
        val: {
          cid: '8bc56739-de61-42e9-b3ee-f4f54cb17ca7',
          typ: 'module',
          sub: 'moduleB',
          val: '',
        },
      },
    ],
    grid: [
      {
        typ: 'slot',
        sub: 'slot_9',
        val: {
          cid: 'a05dcd62-c869-44da-8927-924cde214b34',
          typ: 'module',
          sub: 'moduleS',
          val: '',
        },
      },
      {
        typ: 'slot',
        sub: 'slot_5',
        val: {
          cid: '70b877f4-5226-4dcb-80f4-06b42354ffc4',
          typ: 'module',
          sub: 'moduleH',
          val: '',
        },
      },
      {
        typ: 'slot',
        sub: 'slot_10',
        val: {
          cid: 'c53989d8-29f9-435f-bde1-d11639affbda',
          typ: 'module',
          sub: 'moduleD',
          val: '',
        },
      },
      {
        typ: 'slot',
        sub: 'slot_12',
        val: {
          cid: '03230ca3-63a0-4de9-9ad5-615c038fd99c',
          typ: 'module',
          sub: 'moduleQ',
          val: '',
        },
      },
      {
        typ: 'slot',
        sub: 'slot_13',
        val: {
          cid: 'fe0a0bc7-ed11-4838-9d0f-cd7245a82714',
          typ: 'module',
          sub: 'moduleN',
          val: '',
        },
      },
    ],
    horizontal: [
      {
        typ: 'slot',
        sub: 'slot_1',
        val: {
          cid: 'b8119dc0-5bd9-4047-a2cb-c8226eeb4e80',
          typ: 'module',
          sub: 'moduleA',
          val: '',
        },
      },
      {
        typ: 'slot',
        sub: 'slot_6',
        val: {
          cid: '27166e47-4fd2-4701-8fb2-bf8e3d09e36d',
          typ: 'module',
          sub: 'moduleL',
          val: '',
        },
      },
      {
        typ: 'slot',
        sub: 'slot_8',
        val: {
          cid: '8bc56739-de61-42e9-b3ee-f4f54cb17ca7',
          typ: 'module',
          sub: 'moduleB',
          val: '',
        },
      },
      {
        typ: 'slot',
        sub: 'slot_9',
        val: {
          cid: 'a05dcd62-c869-44da-8927-924cde214b34',
          typ: 'module',
          sub: 'moduleS',
          val: '',
        },
      },
      {
        typ: 'slot',
        sub: 'slot_5',
        val: {
          cid: '70b877f4-5226-4dcb-80f4-06b42354ffc4',
          typ: 'module',
          sub: 'moduleH',
          val: '',
        },
      },
    ],
  },
};
