export default {
  Modules: {
    moduleM: {
      headerText: [
        {
          textItems: [
            {
              text: 'YOUR UNIFORM PLACE',
              style: '',
              __typename: 'StyledText',
            },
          ],
          icon: {
            placement: '',
            icon: '',
            __typename: 'Icon',
          },
          link: {
            url:
              'https://www.childrensplace.com/us/search/all-clearance?icid=hp_s15_buttonnlivetext_searchall_070819_clearance',
            title: 'ALL CLEARANCE',
            target: '_blank',
            __typename: 'Link',
            to:
              '/search?sq=https://www.childrensplace.com/usall-clearance?icid=hp_s15_buttonnlivetext_searchall_070819_clearance',
            asPath:
              'https://www.childrensplace.com/us/search/all-clearance?icid=hp_s15_buttonnlivetext_searchall_070819_clearance',
          },
          __typename: 'HeaderText',
        },
        {
          textItems: [
            {
              text: 'Give Their School Outfits A Head-To-Toe Refresh',
              style: '',
              __typename: 'StyledText',
            },
          ],
          icon: {
            placement: '',
            icon: '',
            __typename: 'Icon',
          },
          link: {
            url:
              'https://www.childrensplace.com/us/search/all-clearance?icid=hp_s15_buttonnlivetext_searchall_070819_clearance',
            title: 'Give Their School Outfits A Head-To-Toe Refresh',
            target: '_blank',
            __typename: 'Link',
            to:
              '/search?sq=https://www.childrensplace.com/usall-clearance?icid=hp_s15_buttonnlivetext_searchall_070819_clearance',
            asPath:
              'https://www.childrensplace.com/us/search/all-clearance?icid=hp_s15_buttonnlivetext_searchall_070819_clearance',
          },
          __typename: 'HeaderText',
        },
      ],
      promoBanner: [
        {
          link: {
            url: '/c/kids-holiday-dress-up-all',
            title: '',
            __typename: 'Link',
            to: '/c?cid=kids-holiday-dress-up-all',
            asPath: '/c/kids-holiday-dress-up-all',
          },
          textItems: [
            {
              text: 'ALL UNIFORMS',
              style: 'medium_text_semibold',
              __typename: 'StyledText',
            },
            {
              text: '60% OFF',
              style: 'fixed_medium_text_black',
              __typename: 'StyledText',
            },
          ],
          __typename: 'PromoBanner',
        },
      ],
      divTabs: [
        {
          text: {
            text: 'GIRL',
            __typename: 'Text',
          },
          category: {
            cat_id: '47511',
            __typename: 'CatID',
          },
          singleCTAButton: {
            url: '/',
            text: 'GIRL',
            target: '',
            title: '',
            __typename: 'Button',
          },
          __typename: 'DivTabs',
        },
        {
          text: {
            text: 'TODDLER GIRL',
            __typename: 'Text',
          },
          category: {
            cat_id: '47512',
            __typename: 'CatID',
          },
          singleCTAButton: {
            url: '/',
            text: 'TODDLER GIRL',
            target: '',
            title: '',
            __typename: 'Button',
          },
          __typename: 'DivTabs',
        },
        {
          text: {
            text: 'BOY',
            __typename: 'Text',
          },
          category: {
            cat_id: '47513',
            __typename: 'CatID',
          },
          singleCTAButton: {
            url: '/',
            text: 'BOY',
            target: '',
            title: '',
            __typename: 'Button',
          },
          __typename: 'DivTabs',
        },
        {
          text: {
            text: 'TODDLER BOY',
            __typename: 'Text',
          },
          category: {
            cat_id: '47514',
            __typename: 'CatID',
          },
          singleCTAButton: {
            url: '/',
            text: 'TODDLER BOY',
            target: '',
            title: '',
            __typename: 'Button',
          },
          __typename: 'DivTabs',
        },
      ],
      singleCTAButton: {
        url: '/c/baby-clothes',
        text: 'SHOP ALL',
        title: '',
        target: '',
        __typename: 'Button',
      },
      moduleName: 'moduleM',
      moduleClassName: '',
    },
  },
  productTabList: {
    '47511': [
      {
        uniqueId: 'kit2',
        product_name: 'Kit2',
        seo_token: 'Kit2-kit2',
        prodpartno: 'kit2',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=Kit2-kit2',
        pdpAsPath: '/p/Kit2-kit2',
      },
      {
        uniqueId: 'Kit503',
        product_name: 'Kit503 - Single Parent with more Style',
        seo_token: 'Kit503---Single-Parent-with-more-Style-Kit503',
        prodpartno: 'Kit503',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=Kit503---Single-Parent-with-more-Style-Kit503',
        pdpAsPath: '/p/Kit503---Single-Parent-with-more-Style-Kit503',
      },
      {
        uniqueId: 'Kit502',
        product_name: 'Asha - Kit502 - Multi Items',
        seo_token: 'Asha---Kit502---Multi-Items-Kit502',
        prodpartno: 'Kit502',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=Asha---Kit502---Multi-Items-Kit502',
        pdpAsPath: '/p/Asha---Kit502---Multi-Items-Kit502',
      },
      {
        uniqueId: 'Kit501',
        product_name: 'Asha - Kit501 - One Item',
        seo_token: 'Asha---Kit501---One-Item-Kit501',
        prodpartno: 'Kit501',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=Asha---Kit501---One-Item-Kit501',
        pdpAsPath: '/p/Asha---Kit501---One-Item-Kit501',
      },
      {
        uniqueId: 'Kit34',
        product_name: 'US 14',
        seo_token: 'US-14-Kit34',
        prodpartno: 'Kit34',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-14-Kit34',
        pdpAsPath: '/p/US-14-Kit34',
      },
      {
        uniqueId: 'Kit33',
        product_name: 'US 13',
        seo_token: 'US-13-Kit33',
        prodpartno: 'Kit33',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-13-Kit33',
        pdpAsPath: '/p/US-13-Kit33',
      },
      {
        uniqueId: 'Kit31',
        product_name: 'US 11',
        seo_token: 'US-11-Kit31',
        prodpartno: 'Kit31',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-11-Kit31',
        pdpAsPath: '/p/US-11-Kit31',
      },
      {
        uniqueId: 'Kit30',
        product_name: 'US 10',
        seo_token: 'US-10-Kit30',
        prodpartno: 'Kit30',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-10-Kit30',
        pdpAsPath: '/p/US-10-Kit30',
      },
    ],
    '47514': [
      {
        uniqueId: 'Kit502',
        product_name: 'Asha - Kit502 - Multi Items',
        seo_token: 'Asha---Kit502---Multi-Items-Kit502',
        prodpartno: 'Kit502',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=Asha---Kit502---Multi-Items-Kit502',
        pdpAsPath: '/p/Asha---Kit502---Multi-Items-Kit502',
      },
      {
        uniqueId: 'Kit501',
        product_name: 'Asha - Kit501 - One Item',
        seo_token: 'Asha---Kit501---One-Item-Kit501',
        prodpartno: 'Kit501',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=Asha---Kit501---One-Item-Kit501',
        pdpAsPath: '/p/Asha---Kit501---One-Item-Kit501',
      },
      {
        uniqueId: 'Kit34',
        product_name: 'US 14',
        seo_token: 'US-14-Kit34',
        prodpartno: 'Kit34',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-14-Kit34',
        pdpAsPath: '/p/US-14-Kit34',
      },
      {
        uniqueId: 'Kit33',
        product_name: 'US 13',
        seo_token: 'US-13-Kit33',
        prodpartno: 'Kit33',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-13-Kit33',
        pdpAsPath: '/p/US-13-Kit33',
      },
      {
        uniqueId: 'Kit31',
        product_name: 'US 11',
        seo_token: 'US-11-Kit31',
        prodpartno: 'Kit31',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-11-Kit31',
        pdpAsPath: '/p/US-11-Kit31',
      },
      {
        uniqueId: 'Kit30',
        product_name: 'US 10',
        seo_token: 'US-10-Kit30',
        prodpartno: 'Kit30',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-10-Kit30',
        pdpAsPath: '/p/US-10-Kit30',
      },
    ],
    '47512': [
      {
        uniqueId: 'Kit27',
        product_name: 'US 7',
        seo_token: 'Updated-SEO-Kit27',
        prodpartno: 'Kit27',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=Updated-SEO-Kit27',
        pdpAsPath: '/p/Updated-SEO-Kit27',
      },
      {
        uniqueId: 'Kit26',
        product_name: 'US 6',
        seo_token: 'US-6-Kit26',
        prodpartno: 'Kit26',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-6-Kit26',
        pdpAsPath: '/p/US-6-Kit26',
      },
      {
        uniqueId: 'Kit25',
        product_name: 'US 5',
        seo_token: 'US-5-Kit25',
        prodpartno: 'Kit25',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-5-Kit25',
        pdpAsPath: '/p/US-5-Kit25',
      },
      {
        uniqueId: 'Kit24',
        product_name:
          'US 4 - Very long name. For testing only. This is US store Collection Bundle. With no Special Characters in name',
        seo_token:
          'US-4---Very-long-name--For-testing-only--This-is-US-store-Collection-Bundle--With-no-Special-Characters-in-name-Kit24',
        prodpartno: 'Kit24',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl:
          '/p?pid=US-4---Very-long-name--For-testing-only--This-is-US-store-Collection-Bundle--With-no-Special-Characters-in-name-Kit24',
        pdpAsPath:
          '/p/US-4---Very-long-name--For-testing-only--This-is-US-store-Collection-Bundle--With-no-Special-Characters-in-name-Kit24',
      },
      {
        uniqueId: 'Kit23',
        product_name: 'US 3',
        seo_token: 'US-3-Kit23',
        prodpartno: 'Kit23',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-3-Kit23',
        pdpAsPath: '/p/US-3-Kit23',
      },
      {
        uniqueId: 'Kit22',
        product_name: 'US 2 - Description Through CSV',
        seo_token: 'US-2---Description-Through-CSV-Kit22',
        prodpartno: 'Kit22',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=US-2---Description-Through-CSV-Kit22',
        pdpAsPath: '/p/US-2---Description-Through-CSV-Kit22',
      },
      {
        uniqueId: 'Kit212',
        product_name: '212 - Same Parent Product Sequence changed',
        seo_token: '212---Same-Parent-Product-Sequence-changed-Kit212',
        prodpartno: 'Kit212',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=212---Same-Parent-Product-Sequence-changed-Kit212',
        pdpAsPath: '/p/212---Same-Parent-Product-Sequence-changed-Kit212',
      },
    ],
    '47513': [
      {
        uniqueId: 'Kit211',
        seo_token: 'Asha---Kit211-in-both-US-and-CA-Kit211',
        prodpartno: 'Kit211',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        product_name: 'Asha - Kit211 in both US and CA',
        pdpUrl: '/p?pid=Asha---Kit211-in-both-US-and-CA-Kit211',
        pdpAsPath: '/p/Asha---Kit211-in-both-US-and-CA-Kit211',
      },
      {
        uniqueId: 'Kit21',
        seo_token: 'US-1-Kit21',
        prodpartno: 'Kit21',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        product_name: 'US 1',
        pdpUrl: '/p?pid=US-1-Kit21',
        pdpAsPath: '/p/US-1-Kit21',
      },
      {
        uniqueId: 'Kit205',
        product_name: '205 - US - 30 Styles Kit',
        seo_token: '205---US---30-Styles-Kit-Kit205',
        prodpartno: 'Kit205',
        imageUrl: ['https://test5.childrensplace.com/image/upload/fill_rvnwi1.png'],
        pdpUrl: '/p?pid=205---US---30-Styles-Kit-Kit205',
        pdpAsPath: '/p/205---US---30-Styles-Kit-Kit205',
      },
    ],
    completed: {
      '47511': false,
      '47502|505520': false,
    },
    '47502|505520': [],
    errors: {
      '47511': null,
      '47502|505520': null,
    },
  },
};
