const giftCards = [
  {
    accountNo: '***********8431',
    billingAddressId: 2282167,
    addressDetails: {
      addressLine1: '57 Hutton Street',
      addressLine2: '',
      city: 'Jersey City',
      country: 'US',
      firstName: 'sachin',
      lastName: 'eawal',
      phone1: '2029291111',
      state: 'NJ',
      zipCode: '07307',
    },
    ccBrand: 'Amex',
    ccType: 'COMPASSAMEX',
    creditCardId: 915655,
    defaultInd: true,
    expMonth: '5 ',
    expYear: '2023',
    nameOnAccount: '.',
    properties: null,
  },
  {
    accountNo: '***************2517',
    billingAddressId: null,
    addressDetails: null,
    ccBrand: 'GC',
    ccType: 'GiftCard',
    creditCardId: 915656,
    defaultInd: false,
    expMonth: '11',
    expYear: '2037',
    nameOnAccount: '.',
    properties: null,
  },
  {
    accountNo: '************0026',
    billingAddressId: 2282167,
    addressDetails: {
      addressLine1: '57 Hutton Street',
      addressLine2: '',
      city: 'Jersey City',
      country: 'US',
      firstName: 'sachin',
      lastName: 'eawal',
      phone1: '2029291111',
      state: 'NJ',
      zipCode: '07307',
    },
    ccBrand: 'Visa',
    ccType: 'COMPASSVISA',
    creditCardId: 915657,
    defaultInd: false,
    expMonth: '5 ',
    expYear: '2024',
    nameOnAccount: '.',
    properties: null,
  },
];

export default giftCards;
